### ISSUE TITLE
"the discrepancy regarding the upper- and lowercase responses"

### ISSUE THREAD

**Issue by endolith** [mkg33/GSoD#1]
You should just combine the `Yes` and `yes` responses (and the like) and re-make the graphs instead of having these notes.  (in https://github.com/mkg33/GSoD/blob/master/user_survey_summary.pdf)

**Comment by mkg33** [comment]
Thanks for pointing this out. I was aware of it but was (initially) too lazy to correct it. I've fixed it now.
